# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00, -7.8134e-04],
        [ 3.0838e-41,  1.4013e-45,  2.3822e-44],
        [ 1.4013e-45,  2.5223e-44,  2.8026e-44],
        [ 4.4377e+27,  6.2577e-20,  4.3075e-41],
        [ 0.0000e+00,  0.0000e+00, -7.8136e-04]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6643, 0.1227, 0.2892],
        [0.9301, 0.6804, 0.8331],
        [0.9582, 0.6943, 0.5365],
        [0.4745, 0.0180, 0.6081],
        [0.6529, 0.0298, 0.9255]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.6643, 0.1227, 0.2892],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4745, 0.0180, 0.6081],
        [0.6529, 0.0298, 0.9255]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
tensor_1 = torch.Tensor(2, 17)
tensor_1.dtype

torch.float32

In [7]:
tensor_2 = torch.FloatTensor(3, 1)
tensor_2.dtype

torch.float32

In [8]:
tensor_3 = torch.ones((5, 2, 1), dtype=torch.long) * 7
tensor_3

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [9]:
tensor_4 = torch.ByteTensor(5,)

tensor_4[1:3] = 1

tensor_4

tensor([ 81,   1,   1, 229, 242], dtype=torch.uint8)

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [10]:
x

tensor([[0.6643, 0.1227, 0.2892],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4745, 0.0180, 0.6081],
        [0.6529, 0.0298, 0.9255]])

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2470, 0.5441, 0.7385],
        [2.3409, 2.6951, 2.2037],
        [2.9105, 2.7673, 2.2135],
        [1.2140, 0.6280, 1.3334],
        [0.7076, 0.8240, 1.7153]])


In [12]:
test_1 = torch.ones(5,5)
test_1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
test_2 = torch.full((2, 5), 2)
test_2

tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]])

In [14]:
result = test_1[:2, :] + test_2
result

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

### 2.2 Addition: syntax 2

In [15]:
print(torch.add(x, y))

tensor([[1.2470, 0.5441, 0.7385],
        [2.3409, 2.6951, 2.2037],
        [2.9105, 2.7673, 2.2135],
        [1.2140, 0.6280, 1.3334],
        [0.7076, 0.8240, 1.7153]])


### 2.3 Addition: giving an output tensor

In [16]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2470, 0.5441, 0.7385],
        [2.3409, 2.6951, 2.2037],
        [2.9105, 2.7673, 2.2135],
        [1.2140, 0.6280, 1.3334],
        [0.7076, 0.8240, 1.7153]])


### 2.4 Addition: in-place

adds `x`to `y`

In [17]:
y.add_(x)
print(y)

tensor([[1.2470, 0.5441, 0.7385],
        [2.3409, 2.6951, 2.2037],
        [2.9105, 2.7673, 2.2135],
        [1.2140, 0.6280, 1.3334],
        [0.7076, 0.8240, 1.7153]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [18]:
print(x[:, 1])

tensor([0.1227, 2.0000, 2.0000, 0.0180, 0.0298])


In [19]:
x = torch.full((5, 1), 3)
x

tensor([[3],
        [3],
        [3],
        [3],
        [3]])

In [20]:
y = torch.full((5,1), 1)
y

tensor([[1],
        [1],
        [1],
        [1],
        [1]])

In [21]:
x = torch.clone(y)

print(x)

print(y)

tensor([[1],
        [1],
        [1],
        [1],
        [1]])
tensor([[1],
        [1],
        [1],
        [1],
        [1]])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [22]:
test_1 = torch.full((3,2), 2)
test_2 = torch.full((3,2), 3)
test_2[1,:] = 1

print(test_1)
print(test_2)

tensor([[2, 2],
        [2, 2],
        [2, 2]])
tensor([[3, 3],
        [1, 1],
        [3, 3]])


In [23]:
result = test_1.matmul(test_2)
print(result)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [24]:
result_2 = test_1.matmul(test_2)
print(result_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [25]:
test_1.mul_(test_2)
print(test_1)

tensor([[6, 6],
        [2, 2],
        [6, 6]])


In [26]:
test_1 = torch.full((3,2), 6)
test_2 = torch.full((1,2), 3)
# test_2[1,:] = 1

print(test_1)
print(test_2)

tensor([[6, 6],
        [6, 6],
        [6, 6]])
tensor([[3, 3]])


In [27]:
result = torch.div(test_1, test_2)
print(result)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [28]:
tensor_1 = torch.full((2,4), 2)
tensor_2 = torch.full((4,2), 3)

print(tensor_1)
print(tensor_2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])
tensor([[3, 3],
        [3, 3],
        [3, 3],
        [3, 3]])


In [29]:
result = tensor_1.matmul(tensor_2)
print(result)

tensor([[24, 24],
        [24, 24]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [34]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[1],
        [1],
        [1],
        [1],
        [1]], device='cuda:0')
tensor([[1],
        [1],
        [1],
        [1],
        [1]], device='cuda:0')
tensor([[2],
        [2],
        [2],
        [2],
        [2]], device='cuda:0')
